// Minimal stub to (re)generate a simple README
import { writeFileSync } from 'node:fs';

const content = `# AUTO-GENERATED\n\nThis README was generated by packages/scripts/build-readme.ts.\n\n- Web: apps/web\n- Worker: apps/worker\n- Packages: packages/*\n`;

writeFileSync('README.md', content, 'utf8');
console.log('README.md generated');

